server:
  port: 9010

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: karthikkaliki2000@gmail.com
    password: egfu fdak ontd rxyl # Gmail App Password
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: false
          ssl.enable: true
          ssl.trust: smtp.gmail.com

twilio:
  accountSid: ACdf764349e1db274a1062e2b0314e7a68
  authToken: 25fa89c295316c34828f226cd1e595fa
  messagingServiceSid: MGcf9f454dc0f0705471a819cfd9e8fd81
  # The phone number the messages are sent FROM (if using a standard number instead of M.S. SID)
  fromNumber: +13369758969
